version: '3.4'

services:
  grpc.appmesh.inventorymanager:
    image: ${DOCKER_REGISTRY-}grpcappmeshinventorymanager
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: gRPC.AppMesh.InventoryManager/Dockerfile
    ports:
      - "5000:5000"

  grpc.appmesh.orderprocessor:
    image: ${DOCKER_REGISTRY-}grpcappmeshorderprocessor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: gRPC.AppMesh.OrderProcessor/Dockerfile
    ports:
      - "3000:3000"
    links:
      - "grpc.appmesh.inventorymanager"